version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/ymgyt/cli
    environment:
      GO111MODULE: "on"
      GOBIN: /go/src/github.com/ymgyt/cli
    steps:
      - checkout
      - run:
          name: run test
          command: go test ./...

workflow:
  version: 2
  build:
    jobs:
    - build