version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/ymgyt/cli
    environment:
      GO111MODULE: "on"
      GOBIN: /go/src/github.com/ymgyt/cli
    steps:
      - checkout
      - restore_cache:
          key: mod-{{ "go.sum" }}
      - run:
          name: run test
          command: go test -race -coverprofile=coverage.txt ./...
      - save_cache:
          key: mod-{{ "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)


workflow:
  version: 2
  build:
    jobs:
    - build